services:
  nats:
    image: nats:2
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped

  order-service:
    image: golang:1.25
    working_dir: /app
    command: ["sh", "-c", "go mod download && CGO_ENABLED=1 go run ./cmd/main.go"]
    ports:
      - "8081:8080"
      - "50052:50052"
    environment:
      - ORDER_DB=/app/order.db
      - PAYMENT_GRPC_ADDR=payment-service:50051
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
      - RATE_LIMIT_REQUESTS=10
      - RATE_LIMIT_WINDOW_SEC=60
      - HTTP_PORT=8080
      - GRPC_PORT=50052
      - GONOSUMCHECK=github.com/AQADIL/*
      - GONOSUMDB=github.com/AQADIL/*
      - GOFLAGS=-mod=mod
    volumes:
      - ./order-service:/app
    depends_on:
      - payment-service
      - nats
      - redis

  payment-service:
    image: golang:1.25
    working_dir: /app
    command: ["sh", "-c", "go mod download && CGO_ENABLED=1 go run ./cmd/main.go"]
    ports:
      - "50051:50051"
    environment:
      - PAYMENT_DB=/app/payment.db
      - GRPC_PORT=50051
      - NATS_URL=nats://nats:4222
      - GONOSUMCHECK=github.com/AQADIL/*
      - GONOSUMDB=github.com/AQADIL/*
      - GOFLAGS=-mod=mod
    volumes:
      - ./payment-service:/app

  notification-service:
    image: golang:1.25
    working_dir: /app
    command: ["sh", "-c", "go mod download && CGO_ENABLED=1 go run ./cmd/main.go"]
    environment:
      - NOTIFICATION_DB=/app/notification.db
      - NATS_URL=nats://nats:4222
      - REDIS_URL=redis://redis:6379
      - PROVIDER_MODE=SIMULATED
      - GONOSUMCHECK=github.com/AQADIL/*
      - GONOSUMDB=github.com/AQADIL/*
      - GOFLAGS=-mod=mod
    volumes:
      - ./notification-service:/app
    depends_on:
      - nats
      - redis
